#Cost 100
GET https://youtube.googleapis.com/youtube/v3/search?part=snippet&q=productivity&maxResults=25&key={{youtubeDataAPIKey}} HTTP/1.1


###
#Get video by Id
#Cost 1
GET https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&id=mYfJxlgR2jw&key={{youtubeDataAPIKey}} HTTP/1.1
###
#
POST http://localhost:3000/api/login HTTP/1.1
Authorization: Berear {{exampleDidToken}}
###

#
POST http://localhost:3000/api/stats?videoId=4zH5iYM4wJo HTTP/1.1

###